-- MySQL Script generated by MySQL Workbench
-- Sat Mar  4 01:54:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cep04
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cep04` ;

-- -----------------------------------------------------
-- Schema cep04
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cep04` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cep04` ;

-- -----------------------------------------------------
-- Table `cep04`.`admin_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cep04`.`admin_tbl` ;

CREATE TABLE IF NOT EXISTS `cep04`.`admin_tbl` (
  `admin_id` BIGINT NOT NULL AUTO_INCREMENT,
  `admin_email` VARCHAR(255) NOT NULL,
  `admin_firstname` VARCHAR(255) NOT NULL,
  `admin_lastname` VARCHAR(255) NOT NULL,
  `admin_password` VARCHAR(255) NOT NULL,
  `admin_role` VARCHAR(20) NOT NULL DEFAULT 'ROLE_ADMIN',
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `UK_8dpf74umhcaag2trxqs3bouev` ON `cep04`.`admin_tbl` (`admin_email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cep04`.`batch_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cep04`.`batch_tbl` ;

CREATE TABLE IF NOT EXISTS `cep04`.`batch_tbl` (
  `batch_id` BIGINT NOT NULL AUTO_INCREMENT,
  `batch_created` DATE NOT NULL,
  `batch_description` VARCHAR(1000) NULL DEFAULT NULL,
  `batch_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`batch_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cep04`.`test_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cep04`.`test_tbl` ;

CREATE TABLE IF NOT EXISTS `cep04`.`test_tbl` (
  `test_id` BIGINT NOT NULL AUTO_INCREMENT,
  `test_description` LONGTEXT NULL DEFAULT NULL,
  `test_duration` INT NOT NULL,
  `test_end_date` DATE NOT NULL,
  `test_max_marks` INT NOT NULL,
  `test_start_date` DATE NOT NULL,
  `test_title` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`test_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cep04`.`student_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cep04`.`student_tbl` ;

CREATE TABLE IF NOT EXISTS `cep04`.`student_tbl` (
  `std_prn` BIGINT NOT NULL,
  `std_email` VARCHAR(255) NOT NULL,
  `std_firstname` VARCHAR(255) NOT NULL,
  `std_lastname` VARCHAR(255) NOT NULL,
  `std_password` VARCHAR(255) NOT NULL,
  `std_rollno` VARCHAR(255) NOT NULL,
  `std_role` VARCHAR(20) NOT NULL DEFAULT 'ROLE_STUDENT',
  `batch_id` BIGINT NOT NULL,
  PRIMARY KEY (`std_prn`),
  CONSTRAINT `FK4qyvbjcw6hyvi0u9x10jpoith`
    FOREIGN KEY (`batch_id`)
    REFERENCES `cep04`.`batch_tbl` (`batch_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `UK_gq64826kss2dllfbx9h3odyai` ON `cep04`.`student_tbl` (`std_email` ASC) VISIBLE;

CREATE UNIQUE INDEX `UK_lin4lvhequf24sdf4cp1crrps` ON `cep04`.`student_tbl` (`std_rollno` ASC) VISIBLE;

CREATE INDEX `FK4qyvbjcw6hyvi0u9x10jpoith` ON `cep04`.`student_tbl` (`batch_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cep04`.`question_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cep04`.`question_tbl` ;

CREATE TABLE IF NOT EXISTS `cep04`.`question_tbl` (
  `question_id` BIGINT NOT NULL AUTO_INCREMENT,
  `question_marks` INT NOT NULL,
  `question_text` LONGTEXT NOT NULL,
  PRIMARY KEY (`question_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cep04`.`master_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cep04`.`master_tbl` ;

CREATE TABLE IF NOT EXISTS `cep04`.`master_tbl` (
  `master_id` BIGINT NOT NULL AUTO_INCREMENT,
  `admin_id` BIGINT NOT NULL,
  `question_id` BIGINT NOT NULL,
  `student_prn` BIGINT NOT NULL,
  `test_id` BIGINT NOT NULL,
  PRIMARY KEY (`master_id`),
  CONSTRAINT `FK3kby4pcfr983f7mnpav200eqg`
    FOREIGN KEY (`test_id`)
    REFERENCES `cep04`.`test_tbl` (`test_id`),
  CONSTRAINT `FKawe405ibvefqa3pw2tvdc04t7`
    FOREIGN KEY (`admin_id`)
    REFERENCES `cep04`.`admin_tbl` (`admin_id`),
  CONSTRAINT `FKgnf3n4w373tjtpdv4dqbxj43g`
    FOREIGN KEY (`student_prn`)
    REFERENCES `cep04`.`student_tbl` (`std_prn`),
  CONSTRAINT `FKm8a80305uiha2jgi6ni7e91fv`
    FOREIGN KEY (`question_id`)
    REFERENCES `cep04`.`question_tbl` (`question_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKawe405ibvefqa3pw2tvdc04t7` ON `cep04`.`master_tbl` (`admin_id` ASC) VISIBLE;

CREATE INDEX `FKm8a80305uiha2jgi6ni7e91fv` ON `cep04`.`master_tbl` (`question_id` ASC) VISIBLE;

CREATE INDEX `FKgnf3n4w373tjtpdv4dqbxj43g` ON `cep04`.`master_tbl` (`student_prn` ASC) VISIBLE;

CREATE INDEX `FK3kby4pcfr983f7mnpav200eqg` ON `cep04`.`master_tbl` (`test_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cep04`.`result_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cep04`.`result_tbl` ;

CREATE TABLE IF NOT EXISTS `cep04`.`result_tbl` (
  `result_id` BIGINT NOT NULL AUTO_INCREMENT,
  `result_code_answer` LONGTEXT NULL DEFAULT NULL,
  `result_obtained_marks` INT NULL DEFAULT NULL,
  `result_master_id` BIGINT NOT NULL,
  PRIMARY KEY (`result_id`),
  CONSTRAINT `FKhtvluggn59b5c99md2t178l46`
    FOREIGN KEY (`result_master_id`)
    REFERENCES `cep04`.`master_tbl` (`master_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKhtvluggn59b5c99md2t178l46` ON `cep04`.`result_tbl` (`result_master_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cep04`.`test_case_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cep04`.`test_case_tbl` ;

CREATE TABLE IF NOT EXISTS `cep04`.`test_case_tbl` (
  `case_id` INT NOT NULL AUTO_INCREMENT,
  `case_input` LONGTEXT NOT NULL,
  `case_marks` INT NOT NULL,
  `case_output` LONGTEXT NOT NULL,
  `question_id` BIGINT NOT NULL,
  PRIMARY KEY (`case_id`),
  CONSTRAINT `FKachumwrbixhc6scyeh4df04f7`
    FOREIGN KEY (`question_id`)
    REFERENCES `cep04`.`question_tbl` (`question_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKachumwrbixhc6scyeh4df04f7` ON `cep04`.`test_case_tbl` (`question_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
